MuslimBlog/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Entity_Framework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MuslimBlog.Controllers
{
	[AllowAnonymous]
	public class AboutController : Controller
    {
        AboutManager abm = new AboutManager(new EFAboutDal());
        // GET: About
        public ActionResult Index()
        {
            var aboutcontent = abm.GetList();
            return View(aboutcontent);
        }
		[AllowAnonymous]
		public PartialViewResult Footer()
        {
           var aboutcontentlist= abm.GetList();
            return PartialView(aboutcontentlist);
        }
        public PartialViewResult MeetTheTeam()
        {
            AuthorManager autman = new AuthorManager(new EFAuthorDal());
            var authorlist = autman.GetList();
            return PartialView(authorlist);
        }
        [HttpGet]
        public ActionResult UpdateAboutList()
        {
            var aboutlist = abm.GetList();
            return View(aboutlist);
        }
        [HttpPost]
        public ActionResult UpdateAbout(About p)
        {
            abm.TUpdate(p);
            return RedirectToAction("UpdateAboutList");
        }
    }
}

MuslimBlog/Controllers/AuthorController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Entity_Framework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MuslimBlog.Controllers
{

    public class AuthorController : Controller
    {
        // GET: Author
        BlogManager blogmanager = new BlogManager(new EFBlogDal());
        AuthorManager authormanager = new AuthorManager(new EFAuthorDal());

		[AllowAnonymous]
		public PartialViewResult AuthorAbout(int id)
        {
            var authordetail = blogmanager.GetBlogByID(id);
            return PartialView(authordetail);
        }
		[AllowAnonymous]
		public PartialViewResult  AuthorPopularPost(int id)
        {
            var blogauthorid = blogmanager.GetList().Where(x => x.BlogID == id).Select(y => y.AuthorID).FirstOrDefault();
            
            var authorblogs = blogmanager.GetBlogByAuthor(blogauthorid);
            return PartialView(authorblogs);
        }
		[AllowAnonymous]
		public ActionResult AuthorList()
        {
             var authorlist=authormanager.GetList();
            return View(authorlist);
        }
		[AllowAnonymous]
		[HttpGet]
        public ActionResult AddAuthor()
        {
            return View();
        }
		[AllowAnonymous]
		[HttpPost]
		public ActionResult AddAuthor(Author p)
		{
			AuthorValidator authorValidator = new AuthorValidator();
			ValidationResult results = authorValidator.Validate(p);
			if (results.IsValid)
			{
				authormanager.TAdd(p);
				return RedirectToAction("AuthorList");
			}
			else
			{
				foreach (var item in results.Errors)
				{
					ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
				}
			}
			return View();
			
		}
		[AllowAnonymous]
		[HttpGet]
		public ActionResult AuthorEdit(int id)
        {
            Author author = authormanager.GetByID(id);
            return View(author);
        }
		[AllowAnonymous]
		[HttpPost]
		public ActionResult AuthorEdit(Author p)
		{
			AuthorValidator authorValidator = new AuthorValidator();
			ValidationResult results = authorValidator.Validate(p);
			if (results.IsValid)
			{
				authormanager.TUpdate(p);
				return RedirectToAction("AuthorList");
			}
			else
			{
				foreach (var item in results.Errors)
				{
					ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
				}
			}
			return View();
			
		}

	}
}

MuslimBlog/Controllers/BlogController.cs
using Antlr.Runtime;
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.Entity_Framework;
using EntityLayer.Concrete;
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace MuslimBlog.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        BlogManager bm = new BlogManager(new EFBlogDal());
		CommentManager cm = new CommentManager(new EFCommentDal());

		[AllowAnonymous]
		public ActionResult Index()
        {
            return View();
        }
		[AllowAnonymous]
		public PartialViewResult BlogList(int page=1)
        {
            var blogList = bm.GetList().ToPagedList(page,6);
            return PartialView(blogList);
        }
		[AllowAnonymous]
		public PartialViewResult FeaturedPosts()
        {
            //1.post
          
            var posttitle1 = bm.GetList().OrderByDescending(z=>z.BlogID).Where(x => x.BlogID == 1011).Select(y => y.BlogTitle).FirstOrDefault();
			var postimage1 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1011).Select(y => y.BlogImage).FirstOrDefault();
			var blogpostid1= bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1011).Select(y => y.BlogID).FirstOrDefault();
			var blogdate1 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1011).Select(y => y.BlogDate).FirstOrDefault();
            ViewBag.posttitle1 = posttitle1;
			ViewBag.postimage1 = postimage1;
			ViewBag.blogdate1 = blogdate1;
			ViewBag.blogpostid1 = blogpostid1;

			//2.post

			var posttitle2 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1012).Select(y => y.BlogTitle).FirstOrDefault();
			var postimage2 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1012).Select(y => y.BlogImage).FirstOrDefault();
			var blogpostid2 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1012).Select(y => y.BlogID).FirstOrDefault();
			var blogdate2 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1012).Select(y => y.BlogDate).FirstOrDefault();
			ViewBag.posttitle2 = posttitle2;
			ViewBag.postimage2= postimage2;
			ViewBag.blogdate2 = blogdate2;
			ViewBag.blogpostid2 = blogpostid2;


			//3.post

			var posttitle3 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1014).Select(y => y.BlogTitle).FirstOrDefault();
			var postimage3 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1014).Select(y => y.BlogImage).FirstOrDefault();
			var blogdate3= bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1014).Select(y => y.BlogDate).FirstOrDefault();
			var blogpostid3 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1014).Select(y => y.BlogID).FirstOrDefault();
			ViewBag.blogpostid3 = blogpostid3;
			ViewBag.posttitle3 = posttitle3;
			ViewBag.postimage3 = postimage3;
			ViewBag.blogdate3= blogdate3;

			//4.post

			var posttitle4 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1010).Select(y => y.BlogTitle).FirstOrDefault();
			var postimage4 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1010).Select(y => y.BlogImage).FirstOrDefault();
			var blogdate4 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1010).Select(y => y.BlogDate).FirstOrDefault();
			var blogpostid4 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1010).Select(y => y.BlogID).FirstOrDefault();
			ViewBag.blogpostid4 = blogpostid4;
			ViewBag.posttitle4 = posttitle4;
			ViewBag.postimage4 = postimage4;
			ViewBag.blogdate4= blogdate4;

			//5.post

			var posttitle5 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1006).Select(y => y.BlogTitle).FirstOrDefault();
			var postimage5 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1006).Select(y => y.BlogImage).FirstOrDefault();
			var blogdate5 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1006).Select(y => y.BlogDate).FirstOrDefault();
			var blogpostid5 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.BlogID == 1006).Select(y => y.BlogID).FirstOrDefault();
			ViewBag.blogpostid5 = blogpostid5;
			ViewBag.posttitle5 = posttitle5;
			ViewBag.postimage5 = postimage5;
			ViewBag.blogdate5 = blogdate5;


			return PartialView();
        }
		[AllowAnonymous]
		public PartialViewResult OtherFeaturedPosts()
		{
			return PartialView();
		}

		[AllowAnonymous]
		public ActionResult BlogDetails()
		{

			return View();
		}
		[AllowAnonymous]
		public PartialViewResult BlogCover(int id)
        {
			var BlogDetailsList = bm.GetBlogByID(id);
			return PartialView(BlogDetailsList);
        }
		[AllowAnonymous]
		public PartialViewResult BlogReadAll(int id)
        {
			var BlogDetailsList = bm.GetBlogByID(id);
            return PartialView(BlogDetailsList);
        }
		[AllowAnonymous]
		public ActionResult BlogByCategory(int id)
		{
			var BlogListByCategory = bm.GetBlogByCategory(id);
			var CategoryName = bm.GetBlogByCategory(id).Select(y => y.Category.CategoryName).FirstOrDefault();
			ViewBag.CategoryName = CategoryName;
			var CategoryDesc = bm.GetBlogByCategory(id).Select(y => y.Category.CategoryDescription).FirstOrDefault();
			ViewBag.CategoryDesc = CategoryDesc;
			return View(BlogListByCategory);
		}

		[Authorize]
		public ActionResult AdminBlogList()
		{
			var bloglist = bm.GetList();
			return View(bloglist);
		}
		
		public ActionResult AdminBlogList2()
		{
			var bloglist = bm.GetList();
			return View(bloglist);
		}
		[Authorize(Roles ="A")]
		[HttpGet]
		public ActionResult AddNewBlog()
		{
			Context c = new Context();
			List<SelectListItem>values=(from x in c.Categorys.ToList()
										select new SelectListItem
										{
				                        Text=x.CategoryName,
					                    Value=x.CategoryId.ToString()
                                        }).ToList();
			ViewBag.values = values;

			List<SelectListItem> values2 = (from x in c.Authors.ToList()
										   select new SelectListItem
										   {
											   Text = x.AuthorName,
											   Value = x.AuthorID.ToString()
										   }).ToList();
			ViewBag.values2 = values2;

			return View();
		}
		[HttpPost]
		public ActionResult AddNewBlog(Blog b)
		{
			bm.TAdd(b);
			return RedirectToAction("AdminBlogList");
		}
		public ActionResult DeleteBlog(int id)
		{
			Blog blog = bm.GetByID(id);
			bm.TDelete(blog);
			
			return RedirectToAction("AdminBlogList");
		}
		[AllowAnonymous]
		[HttpGet]
		public ActionResult UpdateBlog(int id)
		{

			Blog blog = bm.GetByID(id);
			Context c = new Context();
			List<SelectListItem> values = (from x in c.Categorys.ToList()
										   select new SelectListItem
										   {
											   Text = x.CategoryName,
											   Value = x.CategoryId.ToString()
										   }).ToList();
			ViewBag.values = values;

			List<SelectListItem> values2 = (from x in c.Authors.ToList()
											select new SelectListItem
											{
												Text = x.AuthorName,
												Value = x.AuthorID.ToString()
											}).ToList();
			ViewBag.values2 = values2;
			return View(blog);
		}
		[HttpPost]
		public ActionResult UpdateBlog(Blog p)
		{
			bm.TUpdate(p);
			return RedirectToAction("AdminBlogList");
		}
		[AllowAnonymous]
		public ActionResult GetCommentByBlog(int id)
		{
			var commentlist = cm.CommentByBlog(id);
			return View(commentlist);
		}
		public ActionResult AuthorBlogList(int id)
		{
			var blogs = bm.GetBlogByAuthor(id);
			return View(blogs);
		}

	}
}

MuslimBlog/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.Concreterepo;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Entity_Framework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MuslimBlog.Controllers
{
    public class CategoryController : Controller
    {
		// GET: Category
		CategoryManager cm = new CategoryManager(new EFCategoryDal());
       
		[AllowAnonymous]
		public PartialViewResult BlogDetailsCategoryList()
        {
            return PartialView();
        }
        public ActionResult AdminCategoryList()
        {
            var categorylist = cm.GetList();
            return View(categorylist);
        }
		[HttpGet]
		public ActionResult AdminCategoryAdd()
		{

			return View();
		}
		[HttpPost]
		public ActionResult AdminCategoryAdd(Category p)
		{
			CategoryValidator categoryValidator = new CategoryValidator();
			ValidationResult results = categoryValidator.Validate(p);
			if (results.IsValid)
			{
              cm.TAdd(p);
			return RedirectToAction("AdminCategoryList");
			}
			else
			{
				foreach(var item in results.Errors)
				{
					ModelState.AddModelError(item.PropertyName,item.ErrorMessage);
				}
			}
			return View();

			
		}
		[AllowAnonymous]
		[HttpGet]
		public ActionResult CategoryEdit(int id)
		{
			Category category = cm.GetByID(id);
			return View(category);
		}
		[AllowAnonymous]
		[HttpPost]
		public ActionResult CategoryEdit(Category p)
		{
			CategoryValidator categoryValidator = new CategoryValidator();
			ValidationResult results = categoryValidator.Validate(p);
			if (results.IsValid)
			{
				cm.TUpdate(p);
				return RedirectToAction("AdminCategoryList");
			}
			else
			{
				foreach (var item in results.Errors)
				{
					ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
				}
			}
			return View();
		}
		public ActionResult CategoryDelete(int id)
		{
			cm.DeleteCategoryBL(id);
			return RedirectToAction("AdminCategoryList");
		}
		public ActionResult CategoryStatusTrue(int id)
		{
			cm.CategoryStatusTrueBL(id);
			return RedirectToAction("AdminCategoryList");
		}

	}
}

MuslimBlog/Controllers/CommentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Entity_Framework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MuslimBlog.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment
        CommentManager cm = new CommentManager(new EFCommentDal());
		[AllowAnonymous]
		public PartialViewResult CommentList(int id)
        {
            var commentlist = cm.CommentByBlog(id);
            return PartialView(commentlist);
        }
        [HttpGet]
        public PartialViewResult LeaveComment(int id)
        {
            ViewBag.id = id;
            return PartialView();
        }
		[AllowAnonymous]
		[HttpPost]
		public PartialViewResult LeaveComment(Comment c)
		{
			c.CommentStatus = true;
            cm.TAdd(c);
			return PartialView();
		}
        public ActionResult AdminCommentListTrue()
        {
            var commentlist = cm.CommentByStatusTrue();
            return View(commentlist);
        }
		public ActionResult AdminCommentListFalse()
		{
			var commentlist = cm.CommentByStatusFalse();
			return View(commentlist);
		}
		public ActionResult StatusChangeToFalse(int id)
		{
            cm.CommentStatusChangeToFalse(id);

            return RedirectToAction("AdminCommentListTrue");
		}
		public ActionResult StatusChangeToTrue(int id)
		{
			cm.CommentStatusChangeToTrue(id);

			return RedirectToAction("AdminCommentListFalse");
		}
	}
}

MuslimBlog/Views/Blog/AddNewBlog.cshtml
@model EntityLayer.Concrete.Blog
@{
    ViewBag.Title = "AddNewBlog";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form class="form-group" method="post">
    @Html.Label("Blog Başlığı")
    @Html.TextBoxFor(x => x.BlogTitle, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.values, new { @class = "form-control" })
    <br />
    @Html.Label("Resim Yolu")
    @Html.TextBoxFor(x => x.BlogImage, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.BlogDate, new { @class = "form-control" })
    <br />
    @Html.Label("Yazar")
    @Html.DropDownListFor(x => x.AuthorID, (List<SelectListItem>)ViewBag.values2, new { @class = "form-control" })
    <br />
    @Html.Label("İçerik")
    @Html.TextAreaFor(x => x.BlogContent, 5, 20, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet </button>
</form>

MuslimBlog/Views/Blog/AdminBlogList.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@{
    ViewBag.Title = "AdminBlogList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2> Blog Listesi</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID </th>,
        <th>BAŞLIK</th>
        <th>KATEGORİ </th>
        <th>TARİH </th>
        <th>SİL </th>
        <th>GÜNCELLE </th>
        <th>DETAYLAR </th>
        <th>YORUMLAR </th>
    </tr>
    @foreach(var item in Model)
            {
        <tr>
            <td>@item.BlogID</td>
            <td>@item.BlogTitle</td>
            <td>@item.Category.CategoryName</td>
            <td>@item.BlogDate.ToShortDateString()</td>
            
            <td><a href="/Blog/DeleteBlog/@item.BlogID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Blog/UpdateBlog/@item.BlogID" class="btn btn-success">Güncelle</a></td>
            <td><a href="~/Blog/BlogDetails/@item.BlogID" class="btn btn-warning">Detaylar</a></td>
            <td><a href="~/Blog/GetCommentByBlog/@item.BlogID" class="btn btn-dark">Yorumlar</a></td>

        </tr>
            }
</table>
<a href="/Blog/AddNewBlog/" class="btn btn-primary">Yeni blog yazısı ekle</a>

MuslimBlog/Views/Blog/AdminBlogList2.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@{
    ViewBag.Title = "AdminBlogList2";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html>



<body class="hold-transition sidebar-mini">



    <!-- Main content -->

    <section class="content">

        <!-- Default box -->

        <div class="card">

            <div class="card-header">

                <h3 class="card-title">BLOG LİSTESİ</h3>

                <div class="card-tools">

                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">

                        <i class="fas fa-minus"></i>

                    </button>

                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">

                        <i class="fas fa-times"></i>

                    </button>

                </div>

            </div>

            <div class="card-body p-0">

                <table class="table table-striped projects">

                    <thead>

                        <tr>

                            <th style="width: 1%">

                                ID

                            </th>

                            <th style="width: 20%">

                                BLOG BAŞLIĞI

                            </th>

                            <th style="width: 18%">

                                YAZAR

                            </th>

                            <th>

                                BEĞENİ ORANI

                            </th>

                            <th style="width: 8%" class="text-center">

                                KATEGORİ

                            </th>

                            <th style="width: 20%">

                            </th>

                        </tr>

                    </thead>

                    <tbody>
                        @foreach(var item in Model)
                        {
                            <tr>

                                <td>

                                    @item.BlogID

                                </td>

                                <td>
                                    @item.BlogTitle
                                </td>

                                <td>

                                    <ul class="list-inline">

                                        <li class="list-inline-item">


                                            <img alt="Avatar" class="table-avatar" src="@item.Author.AuthorImage">
                                               -   @item.Author.AuthorName
                                        </li>

                                    </ul>

                                </td>

                                <td class="project_progress">

                                    <div class="progress progress-sm">

                                        <div class="progress-bar bg-green" role="progressbar" aria-volumenow="57" aria-volumemin="0" aria-volumemax="100" style="width: 57%">

                                        </div>

                                    </div>

                                    <small>

                                        57% Complete

                                    </small>

                                </td>

                                <td class="project-state">

                                    <span class="badge badge-success">@item.Category.CategoryName</span>

                                </td>

                                <td class="project-actions text-right">

                                    <a class="btn btn-primary btn-sm" href="/Blog/BlogDetails/@item.BlogID">

                                        <i class="fas fa-folder">

                                        </i>

                                        YAZILAR

                                    </a>

                                    <a class="btn btn-info btn-sm" href="/Blog/UpdateBlog/@item.BlogID">

                                        <i class="fas fa-pencil-alt">

                                        </i>

                                        DÜZENLE

                                    </a>

                                    <a class="btn btn-danger btn-sm" href="/Blog/DeleteBlog/@item.BlogID" >

                                        <i class="fas fa-trash">

                                        </i>

                                        SİL

                                    </a>

                                </td>

                            </tr>
                        }
                    </tbody>


                </table>

            </div>

            <!-- /.card-body -->

        </div>

        <!-- /.card -->

    </section>

</body>

</html>

MuslimBlog/Views/Blog/BlogByCategory.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@{
    ViewBag.Title = "BlogByCategory";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="py-5 bg-light">
    <div class="container">
        <div class="row">


            <div class="col-md-6">
                <span>Kategori</span>

                <h3>@ViewBag.CategoryName</h3>
                <p>@ViewBag.CategoryDesc</p>

            </div>
        </div>
    </div>
</div>
<div class="site-section bg-white">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 mb-4">
                    <div class="entry2">
                        <a href="/Blog/BlogDetails/@item.BlogID"><img src="@item.BlogImage" alt="Image" style="width:400px; height:300px; " class="img-fluid rounded"></a>
                        <div class="excerpt">
                            <span class="post-category text-white bg-secondary mb-3">@item.Category.CategoryName</span>

                            <h2><a href="/Blog/BlogDetails/@item.BlogID">@item.BlogTitle</a></h2>
                            <div class="post-meta align-items-center text-left clearfix">
                                <figure class="author-figure mb-0 mr-3 float-left"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                                <span class="d-inline-block mt-1"> <a href="#">@item.Author.AuthorName</a></span>
                                <span>&nbsp;-&nbsp;@(((DateTime)item.BlogDate).ToString("dd-MMM-yyyy")) </span>
                            </div>

                            <p>>@item.BlogContent.Substring(0, item.BlogContent.Substring(0, 200).LastIndexOf(""))...</p>
                            <p><a href="#">Devamını Oku</a></p>
                        </div>
                    </div>
                </div>
            }

        </div>

    </div>
</div>
@Html.Action("Footer", "About")

MuslimBlog/Views/Blog/BlogCover.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
    @foreach (var item in Model)
    {
<div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('@item.BlogImage');">
    <div class="container">
        <div class="row same-height justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="post-entry text-center">
                    <span class="post-category text-white bg-success mb-3">@item.Category.CategoryName</span>
                    <h1 class="mb-4"><a href="#">@item.BlogTitle.</a></h1>
                    <div class="post-meta align-items-center text-center">
                        <figure class="author-figure mb-0 mr-3 d-inline-block"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                        <span class="d-inline-block mt-1">@item.Author.AuthorName</span>
                        <span>&nbsp;-&nbsp; @(((DateTime)item.BlogDate).ToString("dd-MMM-yyyy"))</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    }

MuslimBlog/Views/Blog/BlogDetails.cshtml
@{
    ViewBag.Title = "BlogDetails";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@Html.Action("BlogCover", "Blog")

<section class="site-section py-lg">
    <div class="container">

        <div class="row blog-entries element-animate">

            <div class="col-md-12 col-lg-8 main-content">
                @Html.Action("BlogReadAll", "Blog")

                @Html.Action("CommentList", "Comment")
            </div>
            <div class="col-md-12 col-lg-4 sidebar">
                @Html.Action("AuthorAbout", "Author")
                @Html.Action("AuthorPopularPost", "Author")
                @Html.Action("BlogDetailsCategoryList", "Category")
            </div>
        </div>
    </div>
</section>
@*Html.Action("OtherFeaturedPosts", "Blog")*@
@Html.Action("AddMail", "MailSubscribe")
@Html.Action("Footer", "About")

MuslimBlog/Views/Blog/BlogReadAll.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
    @foreach (var item in Model)
    {
<div class="post-content-body">
    <p>@item.BlogContent </p>

    <div class="row mb-5 mt-5">
        <div class="col-md-12 mb-4">
            <img src="@item.BlogImage" alt="Image placeholder" class="img-fluid rounded">
        </div>

    </div>
    
</div>

    }

MuslimBlog/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}


@Html.Action("FeaturedPosts", "Blog")
@Html.Action("BlogList", "Blog")

@Html.Action("AddMail", "MailSubscribe")
@Html.Action("Footer", "About")